# Netlify configuration for SKAN.AL customer app
[build]
  base = "skan-ecosystem/customer-app"
  command = "npm install && npm run build"
  publish = "build"

# SPA redirect for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy for development and production
[[redirects]]
  from = "/api/*"
  to = "https://api-mkazmlu7ta-ew.a.run.app/:splat"
  status = 200
  force = true